import Foundation

enum L10n {
    static func languageCode(_ preference: String? = nil) -> String {
        let selected = preference ?? UserDefaults.standard.string(forKey: "appLanguage")
        if selected == SettingsStore.Language.english.rawValue { return "en" }
        if selected == SettingsStore.Language.vietnamese.rawValue { return "vi" }
        let preferred = Locale.preferredLanguages.first?.lowercased() ?? "en"
        return preferred.hasPrefix("vi") ? "vi" : "en"
    }

    static func locale(_ preference: String? = nil) -> Locale {
        Locale(identifier: languageCode(preference) == "vi" ? "vi_VN" : "en_US")
    }

    static func t(_ key: String, _ preference: String? = nil) -> String {
        let table = languageCode(preference) == "vi" ? vi : en
        return table[key] ?? en[key] ?? vi[key] ?? key
    }

    static func f(_ key: String, _ preference: String? = nil, _ args: CVarArg...) -> String {
        String(format: t(key, preference), locale: locale(preference), arguments: args)
    }

    static func duration(_ seconds: Double, preference: String? = nil) -> String {
        let code = languageCode(preference)
        if seconds >= 3600 {
            let value = Int(seconds / 3600)
            return code == "vi" ? "\(value) giờ" : "\(value) hour" + (value == 1 ? "" : "s")
        }
        if seconds >= 60 {
            let value = Int(seconds / 60)
            return code == "vi" ? "\(value) phút" : "\(value) minute" + (value == 1 ? "" : "s")
        }
        let value = Int(seconds)
        return code == "vi" ? "\(value) giây" : "\(value) second" + (value == 1 ? "" : "s")
    }

    static func relativeUpdated(from date: Date, preference: String? = nil) -> String {
        let seconds = Int(Date().timeIntervalSince(date))
        if seconds < 5 { return t("time.justUpdated", preference) }
        if seconds < 60 { return f("time.secondsAgo", preference, seconds) }
        if seconds < 3600 { return f("time.minutesAgo", preference, seconds / 60) }
        return f("time.hoursAgo", preference, seconds / 3600)
    }

    static func resetCountdown(to date: Date, preference: String? = nil) -> String {
        let seconds = max(0, Int(date.timeIntervalSinceNow))
        if seconds <= 0 { return t("quota.resetSoon", preference) }
        let days = seconds / 86_400
        let hours = (seconds % 86_400) / 3_600
        let minutes = (seconds % 3_600) / 60
        if days > 0 { return f("quota.resetInDaysHours", preference, days, hours) }
        if hours > 0 { return f("quota.resetInHoursMinutes", preference, hours, minutes) }
        return f("quota.resetInMinutes", preference, minutes)
    }

    static func windowLabel(_ label: String, preference: String? = nil) -> String {
        replace(label, using: languageCode(preference) == "vi" ? windowEnToVi : windowViToEn)
    }

    /// Localizes provider-generated copy without coupling network adapters to
    /// the UI language. Providers keep stable raw labels/errors; views call
    /// this at presentation boundaries for errors, subtitles, plan names, and
    /// service-status text.
    static func providerText(_ text: String, preference: String? = nil) -> String {
        let isVietnamese = languageCode(preference) == "vi"
        let phrases = isVietnamese ? providerEnToVi : providerViToEn
        let windows = isVietnamese ? windowEnToVi : windowViToEn
        return replace(replace(text, using: phrases), using: windows)
    }

    static func dayMonth(_ date: Date, preference: String? = nil) -> String {
        let formatter = DateFormatter()
        formatter.locale = locale(preference)
        formatter.dateFormat = languageCode(preference) == "vi" ? "d MMM" : "MMM d"
        return formatter.string(from: date)
    }

    private static func replace(_ source: String, using replacements: [(String, String)]) -> String {
        replacements.reduce(source) { value, replacement in
            value.replacingOccurrences(of: replacement.0, with: replacement.1)
        }
    }

    // Ordered longest-first so specific provider phrases win before generic
    // unit/word replacements.
    private static let windowViToEn: [(String, String)] = [
        ("Credits mua thêm", "Purchased credits"),
        ("Ngân sách tháng", "Monthly budget"),
        ("Số dư tháng", "Monthly balance"),
        ("Yêu cầu/phút", "Requests/min"),
        ("Tokens/phút", "Tokens/min"),
        ("Cache hit/phút", "Cache hits/min"),
        ("Chi tiết (30d)", "Details (30d)"),
        ("Hạn mức key", "Key limit"),
        ("Vượt hạn mức", "Overage"),
        ("Tín dụng", "Credits"),
        ("Số dư", "Balance"),
        ("Yêu cầu", "Requests"),
        ("Gia hạn", "Renewal"),
        ("Hết hạn", "Expires"),
        ("Giới hạn", "Limit"),
        ("Tháng", "Month"),
        ("Tuần", "Week"),
        ("tuần", "weeks"),
        ("ngày", "days"),
        ("giờ", "hours"),
        ("phút", "minutes"),
    ]

    private static let windowEnToVi: [(String, String)] = [
        ("Professional voices", "Giọng chuyên nghiệp"),
        ("Purchased credits", "Tín dụng mua thêm"),
        ("Monthly budget", "Ngân sách tháng"),
        ("Monthly balance", "Số dư tháng"),
        ("Voice slots", "Vị trí giọng nói"),
        ("Cache hits/min", "Cache hit/phút"),
        ("Requests/min", "Yêu cầu/phút"),
        ("Tokens/min", "Token/phút"),
        ("Bonus Credits", "Tín dụng thưởng"),
        ("Details (30d)", "Chi tiết (30 ngày)"),
        ("Requests (30d)", "Yêu cầu (30 ngày)"),
        ("Audio (30d)", "Âm thanh (30 ngày)"),
        ("Key limit", "Hạn mức key"),
        ("On-demand", "Theo nhu cầu"),
        ("Overage", "Vượt hạn mức"),
        ("Token Plan", "Gói token"),
        ("Credits", "Tín dụng"),
        ("Requests", "Yêu cầu"),
        ("Balance", "Số dư"),
        ("Renewal", "Gia hạn"),
        ("Expires", "Hết hạn"),
        ("14 days", "14 ngày"),
        ("5 hours", "5 giờ"),
        ("Month", "Tháng"),
        ("Week", "Tuần"),
        ("Limit", "Giới hạn"),
        ("Rolling", "Chu kỳ"),
        ("Auto", "Tự động"),
        ("hours", "giờ"),
        ("minutes", "phút"),
        ("days", "ngày"),
        ("weeks", "tuần"),
    ]

    private static let providerViToEn: [(String, String)] = [
        ("Hết thời gian chờ xác thực. Vui lòng thử lại.", "Authentication timed out. Please try again."),
        ("Warning: .bak hiện tại không parse được, sẽ bị ghi đè.", "Warning: the current .bak file cannot be parsed and will be overwritten."),
        ("Phản hồi từ máy chủ không đúng định dạng.", "The server returned an invalid response."),
        ("Yêu cầu đăng nhập bị từ chối.", "The sign-in request was denied."),
        ("Máy chủ trả về lỗi HTTP", "The server returned HTTP"),
        ("URL yêu cầu không hợp lệ.", "The request URL is invalid."),
        ("Hapo endpoint chưa được cấu hình trong bản build", "Hapo endpoint is not configured in this build"),
        ("Hết số dư — cần nạp thêm", "Balance exhausted — top up required"),
        ("Antigravity OAuth client chưa được cấu hình", "Antigravity OAuth client is not configured"),
        ("Claude chưa có dữ liệu quota", "Claude has no quota data"),
        ("Copilot chưa có dữ liệu quota", "Copilot has no quota data"),
        ("Codex chưa có dữ liệu quota", "Codex has no quota data"),
        ("Codex CLI không trả dữ liệu", "Codex CLI returned no data"),
        ("Token Codex hết hạn — chạy `codex` để đăng nhập lại", "Codex token expired — run `codex` to sign in again"),
        ("Chưa đăng nhập Codex — chạy `codex` để đăng nhập", "Not signed in to Codex — run `codex` to sign in"),
        ("Phiên đăng nhập hết hạn — vui lòng đăng nhập lại claude.ai.", "Session expired — sign in to claude.ai again."),
        ("Không tìm thấy tổ chức Claude cho tài khoản này.", "Could not find a Claude organization for this account."),
        ("Chỉ hỗ trợ macOS.", "Only macOS is supported."),
        ("Tất cả model đều nằm trong danh sách loại trừ", "All models are excluded"),
        ("Chưa cấu hình token và không tìm thấy cookie trình duyệt", "No token or browser cookie is configured"),
        ("Endpoint không tồn tại (HTTP 404). Kilo tRPC path có thể đã thay đổi.", "Endpoint not found (HTTP 404). The Kilo tRPC path may have changed."),
        ("Kilo API tạm thời không khả dụng", "Kilo API is temporarily unavailable"),
        ("Xác thực thất bại", "Authentication failed"),
        ("Response không phải HTTP", "Response is not HTTP"),
        ("Response JSON không hợp lệ", "Invalid JSON response"),
        ("Response thiếu trường", "Response is missing required fields"),
        ("Response không hợp lệ", "Invalid response"),
        ("Phản hồi không hợp lệ", "Invalid response"),
        ("Token chứa ký tự không hợp lệ", "Token contains invalid characters"),
        ("Không có model nào trong response", "The response contains no models"),
        ("Không có quota buckets trong response", "The response contains no quota buckets"),
        ("Không có dữ liệu quota", "No quota data"),
        ("Không có dữ liệu credits", "No credits data"),
        ("Không có thông tin số dư", "No balance information"),
        ("Không lấy được dữ liệu", "Could not fetch data"),
        ("Không lấy được quota", "Could not fetch quota"),
        ("Không lấy được usage", "Could not fetch usage"),
        ("Không lấy được workspace", "Could not fetch workspace"),
        ("Không tìm thấy cookie đăng nhập", "Could not find a sign-in cookie for"),
        ("Không tìm thấy session cookie", "Could not find a session cookie"),
        ("Không tìm thấy thông tin usage", "Could not find usage information"),
        ("Không tìm thấy", "Could not find"),
        ("Không thể phân tích dữ liệu", "Could not parse data for"),
        ("Không phân tích được dữ liệu", "Could not parse data for"),
        ("Không parse được", "Could not parse"),
        ("Không thể đọc", "Could not read"),
        ("Không đọc được", "Could not read"),
        ("Không chạy được", "Could not run"),
        ("Không khởi động được", "Could not start"),
        ("Không nhận được", "Did not receive"),
        ("File credentials không đọc được", "Credentials file could not be read"),
        ("Output trống từ", "Empty output from"),
        ("kiro-cli thoát với code", "kiro-cli exited with code"),
        ("timeout chờ callback từ browser", "timed out waiting for the browser callback"),
        ("đổi token thất bại", "token exchange failed"),
        ("lấy quota thất bại", "quota fetch failed"),
        ("parse thất bại", "parse failed"),
        ("Chưa cấu hình AWS credentials", "AWS credentials are not configured"),
        ("Chưa cấu hình API key", "API key is not configured for"),
        ("Chưa cấu hình token", "Token is not configured"),
        ("Chưa đăng nhập", "Not signed in to"),
        ("Chưa cài", "Not installed:"),
        ("Chưa có", "No"),
        ("chưa được cấu hình", "is not configured"),
        ("Không có", "No"),
        ("không trả dữ liệu", "returned no data"),
        ("không phản hồi", "did not respond"),
        ("không hợp lệ", "is invalid"),
        ("không khả dụng", "is unavailable"),
        ("không tồn tại", "does not exist"),
        ("không nhận ra", "is not recognized"),
        ("không hoàn tất", "did not complete"),
        ("không khớp", "does not match"),
        ("thất bại", "failed"),
        ("hết hạn", "expired"),
        ("trên trình duyệt", "in the browser"),
        ("trong trình duyệt", "in the browser"),
        ("trong bản build", "in this build"),
        ("đang chạy", "running"),
        ("đang listen", "listening"),
        ("đăng nhập lại", "sign in again"),
        ("đăng nhập bằng", "sign in with"),
        ("đăng nhập", "sign in"),
        ("mở app", "open the app"),
        ("Cài ", "Install "),
        ("Cần ", "Requires "),
        ("cần ", "requires "),
        (" hoặc ", " or "),
        (" và ", " and "),
        (" từ ", " from "),
        (" của ", " for "),
        (" cho key này", " for this key"),
        (" cho tài khoản này", " for this account"),
        ("Tài khoản", "Account"),
        ("tài khoản", "account"),
        ("tổ chức", "organization"),
        ("Dữ liệu", "Data"),
        ("dữ liệu", "data"),
        ("thông tin", "information"),
        ("Định dạng", "Format"),
        ("Thiếu", "Missing"),
        ("Kiểm tra lại", "Check"),
        ("kiểm tra", "check"),
        ("Lỗi tạo URL", "Could not create URL"),
        ("Lỗi phân tích dữ liệu", "Data parsing error"),
        ("Lỗi mạng", "Network error"),
        ("Lỗi API", "API error"),
        ("Parse lỗi", "Parse error"),
        ("Parse thất bại", "Parse failed"),
        ("Sắp reset", "Resetting soon"),
        ("Tự động", "Automatic"),
        ("Phiên", "Session"),
        ("Đã dùng", "Used"),
        ("còn lại", "remaining"),
        ("Trả:", "Paid:"),
        ("Tặng:", "Granted:"),
        ("Nâng cấp tại", "Upgrade at"),
        ("Đang bật", "Enabled"),
        ("không xác định", "unknown"),
        ("Lỗi", "Error"),
        ("lỗi", "error"),
    ]

    private static let providerEnToVi: [(String, String)] = [
        ("All Systems Operational", "Tất cả hệ thống hoạt động bình thường"),
        ("Partial Outage", "Gián đoạn một phần"),
        ("Major Outage", "Gián đoạn nghiêm trọng"),
        ("Authentication timed out. Please try again.", "Hết thời gian chờ xác thực. Vui lòng thử lại."),
        ("The server returned an invalid response.", "Máy chủ trả về phản hồi không hợp lệ."),
        ("The sign-in request was denied.", "Yêu cầu đăng nhập bị từ chối."),
        ("Response is missing required fields", "Phản hồi thiếu trường bắt buộc"),
        ("Response is not HTTP", "Phản hồi không phải HTTP"),
        ("Invalid JSON response", "Phản hồi JSON không hợp lệ"),
        ("Invalid response", "Phản hồi không hợp lệ"),
        ("Authentication failed", "Xác thực thất bại"),
        ("Token is not configured", "Chưa cấu hình token"),
        ("API key is not configured for", "Chưa cấu hình API key cho"),
        ("Not signed in to", "Chưa đăng nhập"),
        ("Could not find", "Không tìm thấy"),
        ("Could not fetch", "Không lấy được"),
        ("Could not parse", "Không thể phân tích"),
        ("Could not read", "Không thể đọc"),
        ("Could not run", "Không thể chạy"),
        ("Network error", "Lỗi mạng"),
        ("Network:", "Mạng:"),
        ("Resetting soon", "Sắp đặt lại"),
        ("Balance exhausted — top up required", "Hết số dư — cần nạp thêm"),
        ("Code review", "Đánh giá mã"),
        ("reset credits", "lượt đặt lại"),
        ("credits", "tín dụng"),
        ("Operational", "Hoạt động bình thường"),
        ("remaining", "còn lại"),
        ("Paid:", "Đã trả:"),
        ("Granted:", "Được tặng:"),
        ("Enabled", "Đang bật"),
        ("Automatic", "Tự động"),
        ("Session", "Phiên"),
    ]

    private static let vi: [String: String] = [
        "language.system": "Theo hệ thống",
        "language.english": "Tiếng Anh",
        "language.vietnamese": "Tiếng Việt",
        "settings.tab.general": "Cài chung",
        "settings.tab.providers": "Nhà cung cấp",
        "settings.tab.display": "Hiển thị",
        "settings.tab.advanced": "Nâng cao",
        "settings.tab.about": "Giới thiệu",
        "settings.tab.debug": "Debug",
        "settings.tab.codex": "Codex",
        "settings.tab.aiCoding": "AI Coding",
        "settings.section.system": "Hệ thống",
        "settings.section.usage": "Sử dụng",
        "settings.section.automation": "Tự động",
        "settings.section.privacy": "Riêng tư",
        "settings.section.developer": "Nhà phát triển",
        "settings.section.files": "Tệp",
        "settings.section.menuBar": "Menu bar",
        "settings.section.links": "Liên kết",
        "settings.section.setup": "Thiết lập",
        "settings.section.account": "Tài khoản",
        "settings.codex.autoPrime.title": "Tự động kích hoạt window 5h",
        "settings.codex.autoPrime.toggle": "Tự kích hoạt",
        "settings.codex.autoPrime.toggleSubtitle": "Gửi 1 request nhỏ mỗi ngày để bắt đầu đồng hồ 5h đúng giờ làm việc.",
        "settings.codex.autoPrime.time": "Giờ kích hoạt",
        "settings.codex.autoPrime.timeSubtitle": "Chỉ kích hoạt khi window 5h đang nghỉ (chưa dùng).",
        "notification.codexPrimed.title": "Đã kích hoạt Codex 5h",
        "notification.codexPrimed.body": "Window 5h đã được kích hoạt lúc %@.",
        "settings.section.quotaWarnings": "Cảnh báo quota",
        "settings.refresh.manual": "Thủ công",
        "settings.manualRefreshHint": "Đã tắt tự làm mới — dùng nút làm mới trong popover.",
        "settings.refreshOnOpen.title": "Làm mới khi mở",
        "settings.refreshOnOpen.subtitle": "Làm mới tất cả nhà cung cấp mỗi lần mở popover.",
        "settings.quitApp": "Thoát BirdNion",
        "settings.warningSound.title": "Phát âm thanh",
        "settings.warningSound.subtitle": "Kèm âm thanh khi cảnh báo quota.",
        "settings.warningAlert.title": "Cảnh báo trên màn hình",
        "settings.warningAlert.subtitle": "Hiện cảnh báo ngắn giữa màn hình khi chạm ngưỡng.",
        "settings.section.shortcut": "Phím tắt",
        "settings.hotkey.title": "Mở popover",
        "settings.hotkey.subtitle": "Phím tắt toàn cục bật/tắt popover quota.",
        "settings.disableKeychain.title": "Tắt truy cập Keychain",
        "settings.disableKeychain.subtitle": "Debug: bỏ qua đọc Keychain macOS (Claude OAuth, cookie trình duyệt).",
        "settings.storageFootprint.title": "Hiện dung lượng lưu trữ",
        "settings.storageFootprint.subtitle": "Hiện dung lượng dữ liệu trên đĩa của từng nhà cung cấp.",
        "provider.storage": "Dung lượng",
        "provider.storage.none": "Không có dữ liệu cục bộ",
        "about.section.updates": "Cập nhật",
        "about.autoCheck.title": "Tự kiểm tra",
        "about.autoCheck.subtitle": "Kiểm tra bản mới mỗi ngày khi mở app.",
        "about.channel.title": "Kênh cập nhật",
        "about.channel.stable": "Ổn định",
        "about.channel.beta": "Beta",
        "about.checkNow": "Kiểm tra cập nhật",
        "about.checking": "Đang kiểm tra…",
        "about.upToDate": "Bạn đang dùng bản mới nhất.",
        "about.updateAvailable": "Có bản %@",
        "about.openRelease": "Xem bản phát hành",
        "about.updateNow": "Cập nhật ngay",
        "about.checkFailed": "Không kiểm tra được cập nhật.",
        "about.buildDate": "Build %@",
        "providerError.cookieExpiredOrMissing.title": "Cookie hết hạn",
        "providerError.cookieExpiredOrMissing.hint": "Cookie hết hạn — đăng nhập lại trình duyệt",
        "providerError.tokenInvalidOrMissing.title": "Token không hợp lệ",
        "providerError.tokenInvalidOrMissing.hint": "Token sai — dán lại API key",
        "providerError.apiSchemaChanged.title": "Phản hồi lạ",
        "providerError.apiSchemaChanged.hint": "Phản hồi lạ — có thể cần cập nhật app",
        "providerError.networkUnreachableOrTimeout.title": "Lỗi mạng",
        "providerError.networkUnreachableOrTimeout.hint": "Mất mạng hoặc quá thời gian — kiểm tra kết nối",
        "providerError.rateLimited.title": "Bị giới hạn tần suất",
        "providerError.rateLimited.hint": "Bị giới hạn tần suất — đợi rồi thử lại",
        "providerError.unknown.title": "Lỗi không xác định",
        "providerError.unknown.hint": "Lỗi không xác định — xem chi tiết",
        "provider.selfTest": "Kiểm tra",
        "provider.selfTest.running": "Đang kiểm tra…",
        "provider.selfTest.pass": "Đạt",
        "provider.selfTest.fail": "Lỗi",
        "provider.selfTest.disabled": "Bật provider để kiểm tra",
        "notification.providerFailing": "%@ — %@",
        "settings.language.title": "Ngôn ngữ",
        "settings.language.subtitle": "Đổi ngay trong UI; lần mở sau app cũng giữ ngôn ngữ này.",
        "settings.launchAtLogin.title": "Khởi động cùng máy",
        "settings.launchAtLogin.subtitle": "Tự mở BirdNion khi đăng nhập.",
        "settings.refreshFrequency.title": "Tần suất làm mới",
        "settings.refreshFrequency.subtitle": "Mỗi bao lâu app gọi lại nhà cung cấp.",
        "settings.statusChecks.title": "Kiểm tra trạng thái",
        "settings.statusChecks.subtitle": "Poll trang trạng thái của các nhà cung cấp.",
        "settings.sessionNotifications.title": "Thông báo phiên 5 giờ",
        "settings.sessionNotifications.subtitle": "Báo khi phiên quota chạm 0% và khi khôi phục.",
        "settings.quotaWarningNotifications.title": "Thông báo cảnh báo quota",
        "settings.quotaWarningNotifications.subtitle": "Cảnh báo khi còn dưới ngưỡng đã đặt.",
        "settings.warningThreshold.title": "Ngưỡng cảnh báo",
        "settings.warningThreshold.subtitle": "Báo lần đầu khi % còn lại chạm mức này.",
        "settings.criticalThreshold.title": "Ngưỡng nguy hiểm",
        "settings.criticalThreshold.subtitle": "Báo lần nữa khi chạm mức thấp hơn này.",
        "settings.hidePersonalInfo.title": "Ẩn thông tin cá nhân",
        "settings.hidePersonalInfo.subtitle": "Che email tài khoản trên chip và popover.",
        "settings.debugMenu.title": "Hiện mục Debug",
        "settings.debugMenu.subtitle": "Thêm tab Debug để xem log và cache.",
        "settings.developer.footer": "Một số thay đổi kỹ thuật vẫn có thể cần mở lại app.",
        "settings.display.footer": "Khi tắt, menu bar chỉ hiện logo BirdNion.",
        "settings.showPercentInMenuBar.title": "Hiển thị % trên menu bar",
        "settings.showPercentInMenuBar.subtitle": "Lần lượt hiện quota của các provider đang hoạt động; nếu không có dữ liệu thì giữ logo chim.",
        "settings.mergeIcons.title": "Gộp icon nhà cung cấp",
        "settings.mergeIcons.subtitle": "Cài đặt cũ; menu bar hiện dùng tuỳ chọn % phía trên.",
        "settings.switcherShowsIcons.title": "Switcher có icon",
        "settings.switcherShowsIcons.subtitle.on": "Hiện icon khi chuyển nhà cung cấp từ popover.",
        "settings.switcherShowsIcons.subtitle.off": "Bật “Gộp icon” trước.",
        "settings.debug.footer": "Để xem log probe / fetch strategy thật, mở Console.app và filter theo bundle ID.",
        "settings.configFile.title": "File cấu hình",
        "settings.openFinder": "Mở Finder",
        "about.openProject": "Mở trang dự án trên GitHub",
        "about.tagline": "Theo dõi quota AI ngay trên menu bar.",
        "about.version": "phiên bản %@ (%@)",
        "provider.search": "Tìm nhà cung cấp",
        "provider.clearSearch": "Xóa",
        "provider.reorderHelp": "Kéo để sắp xếp nhà cung cấp",
        "provider.choose": "Chọn một nhà cung cấp",
        "provider.enableHelp.on": "Tắt polling cho nhà cung cấp này",
        "provider.enableHelp.off": "Bật polling cho nhà cung cấp này",
        "provider.disabled": "Đã tắt",
        "provider.notLoaded": "Chưa tải",
        "provider.loading": "Đang tải…",
        "provider.error": "Lỗi",
        "provider.errorPrefix": "Lỗi: %@",
        "provider.remaining": "Còn %d%%",
        "provider.status": "Trạng thái",
        "provider.source": "Nguồn",
        "provider.plan": "Gói",
        "provider.planName": "Tên gói",
        "provider.account": "Tài khoản",
        "provider.version": "Phiên bản",
        "provider.kiroContext": "Context window",
        "provider.serviceStatus": "Tình trạng",
        "provider.resetCredits": "Reset khả dụng",
        "provider.codeReview": "Code review",
        "provider.creditsHistory": "Lịch sử credits",
        "provider.buyCredits": "Mua credits",
        "provider.openPage": "Mở trang",
        "provider.updated": "Cập nhật",
        "provider.reloadHelp": "Đọc lại settings.json và làm mới quota",
        "provider.noData.enabled": "Chưa có dữ liệu — bấm làm mới.",
        "provider.noData.disabled": "Đang tắt — không có dữ liệu.",
        "provider.reserve": "%d%% dự phòng",
        "provider.resetAfter": "Reset sau %@",
        "provider.enoughUntilReset": "Đủ dùng đến khi reset",
        "provider.mayRunOut": "Có thể hết trước khi reset",
        "provider.credits": "CREDITS",
        "provider.creditsAvailable": "Credits khả dụng",
        "provider.unlimited": "∞ Không giới hạn",
        "provider.creditsLeft": "%@ còn lại",
        "provider.outOfCredits": "Hết",
        "provider.cost": "CHI PHÍ",
        "provider.usedRemaining": "%d%% đã dùng · còn %@",
        "provider.today": "Hôm nay",
        "provider.last30": "30 ngày",
        "provider.email": "EMAIL",
        "provider.organization": "TỔ CHỨC",
        "provider.login": "LOGIN",
        "provider.accountLabel": "Nhãn tài khoản",
        "provider.accountLabelPlaceholder": "Tùy chọn — để trống để tự suy ra",
        "provider.signIn": "Đăng nhập",
        "provider.codexSignInHint": "Đăng nhập bằng lệnh `codex` trong Terminal.",
        "provider.dataSource": "Nguồn dữ liệu",
        "provider.menuBarMetric": "Menu bar hiển thị",
        "provider.apiRegion": "Khu vực API",
        "provider.refreshEvery": "Làm mới mỗi",
        "provider.defaultGlobal": "Mặc định = theo cài đặt chung (%@)",
        "provider.cookie": "Cookie",
        "provider.cookiePlaceholder": "Dán Cookie: header từ chatgpt.com",
        "provider.cookieClaude": "Cookie Claude",
        "provider.manualCookie": "Cookie header thủ công",
        "provider.manualCookieHelp": "Mở claude.ai trong trình duyệt đã đăng nhập → DevTools → Network → sao chép toàn bộ header `Cookie:`.",
        "provider.keychainOAuth": "Keychain OAuth",
        "provider.openAIWebExtras": "OpenAI web extras",
        "provider.openAIWebExtrasHelp": "Quét chatgpt.com (WebView ẩn) lấy code-review %, credits, lịch sử. Nặng pin/mạng — mặc định tắt.",
        "provider.claudeConfig": "Cấu hình Claude…",
        "provider.token": "Token",
        "provider.tokenPlaceholder": "Dán token vào đây",
        "provider.save": "Lưu",
        "provider.savedSettings": "Đã lưu vào ~/.config/birdnion/settings.json.",
        "provider.saveError": "Lỗi lưu: %@",
        "provider.quotaWarningsFooter": "Dùng ngưỡng chung trừ khi bật tùy chỉnh riêng cho từng cửa sổ.",
        "provider.sessionWindow": "Phiên (5 giờ)",
        "provider.weekWindow": "Tuần",
        "provider.customThresholds": "Tùy chỉnh ngưỡng %@",
        "provider.inherited": "Kế thừa: %@",
        "provider.warning": "Cảnh báo",
        "provider.critical": "Nguy hiểm",
        "provider.accountsFooter": "Mỗi tài khoản đăng nhập riêng. “Thêm tài khoản” mở `codex login` trong trình duyệt; tài khoản hệ thống (~/.codex) không bị ghi đè.",
        "provider.systemAccount": "Tài khoản hệ thống",
        "provider.accountGeneric": "Tài khoản",
        "freemodel.browserAuto": "Trình duyệt (tự động)",
        "freemodel.switchAccount": "Chuyển sang tài khoản này",
        "freemodel.addAccount": "Thêm",
        "freemodel.addHint": "Dán cookie bm_session từ trình duyệt đã đăng nhập freemodel.dev (DevTools → Application → Cookies). Các trình duyệt đang đăng nhập được tự phát hiện ở trên.",
        "freemodel.cookiePlaceholder": "bm_session=… hoặc cả chuỗi Cookie",
        "freemodel.labelPlaceholder": "Nhãn (tuỳ chọn)",
        "freemodel.cookieNeedsSession": "Cookie phải chứa bm_session",
        "elevenlabs.keysLabel": "API keys ElevenLabs",
        "elevenlabs.keysFooter": "Lưu nhiều API key và chuyển nhanh trên popover. Key được lưu riêng (không ghi đè settings chung).",
        "elevenlabs.keysEmpty": "Chưa có API key — dán key bên dưới để thêm.",
        "elevenlabs.keyPlaceholder": "Dán API key ElevenLabs…",
        "elevenlabs.labelPlaceholder": "Nhãn (tuỳ chọn)",
        "elevenlabs.addKey": "Thêm key",
        "elevenlabs.switchKey": "Dùng key này",
        "elevenlabs.activeBadge": "Đang dùng",
        "elevenlabs.popoverTitle": "API keys",
        "provider.systemManaged": "Hệ thống · ~/.codex",
        "provider.appManaged": "Quản lý bởi app",
        "provider.reauth": "Đăng nhập lại",
        "provider.saveManaged": "Lưu thành managed",
        "provider.addAccount": "Thêm tài khoản",
        "provider.waitingLogin": "Đang chờ đăng nhập trong trình duyệt…",
        "provider.addAccountFailed": "Thêm tài khoản thất bại: %@",
        "provider.removeAccount": "Xoá tài khoản",
        "provider.removeSystemAccount": "Xoá đăng nhập hệ thống",
        "provider.removeAccountTitle": "Xoá %@?",
        "provider.removeAccountMessage": "Tài khoản managed sẽ bị xoá khỏi BirdNion.",
        "provider.removeSystemAccountMessage": "File ~/.codex/auth.json sẽ được chuyển sang bản backup để bạn có thể đăng nhập lại.",
        "provider.removeAccountFailed": "Xoá tài khoản thất bại: %@",
        "provider.link.codexUsage": "Trang sử dụng Codex",
        "provider.link.openAIStatus": "Trạng thái OpenAI",
        "provider.link.changelog": "Changelog",
        "provider.link.minimaxPlan": "Trang Token Plan",
        "provider.link.openRouterCredits": "Tín dụng OpenRouter",
        "provider.link.apiKeys": "API keys",
        "provider.link.deepSeekBalance": "Số dư DeepSeek",
        "provider.link.codingPlan": "Coding Plan",
        "provider.link.anthropicStatus": "Trạng thái Anthropic",
        "provider.link.dashboard": "Bảng điều khiển",
        "provider.link.status": "Trạng thái dịch vụ",
        "provider.link.usage": "Trang sử dụng",
        "provider.link.subscription": "Gói đăng ký",
        "provider.link.billing": "Thanh toán",
        "source.auto": "Tự động",
        "source.oauth": "OAuth",
        "source.cli": "CLI",
        "source.codex.auto.subtitle": "OAuth, fallback sang CLI `codex app-server` khi lỗi (mặc định).",
        "source.codex.oauth.subtitle": "Chỉ OAuth (token ~/.codex/auth.json) — không fallback CLI.",
        "source.codex.cli.subtitle": "Chỉ `codex app-server` RPC cục bộ — bỏ qua OAuth.",
        "source.claude.auto.subtitle": "Thử OAuth → Web → CLI, lấy cái đầu tiên thành công.",
        "source.claude.oauth.subtitle": "Dùng OAuth token trong Keychain của Claude Code (mặc định).",
        "source.claude.web.subtitle": "Scrape claude.ai qua cookie Safari/Chrome.",
        "source.claude.cli.subtitle": "Chạy `claude` CLI trong PTY (cần CLI cài đặt).",
        "source.claude.api.subtitle": "Anthropic Admin API (cần nhập key bên dưới).",
        "metric.automatic": "Tự động",
        "metric.session": "Phiên (5 giờ)",
        "metric.weekly": "Tuần",
        "region.china": "Trung Quốc (platform.minimaxi.com)",
        "prompt.never": "Không bao giờ",
        "prompt.onlyOnUserAction": "Chỉ khi bấm",
        "prompt.always": "Luôn hỏi",
        "refresh.default": "Mặc định chung",
        "refresh.30s": "30 giây",
        "refresh.1m": "1 phút",
        "refresh.2m": "2 phút",
        "refresh.5m": "5 phút",
        "refresh.10m": "10 phút",
        "refresh.30m": "30 phút",
        "popover.ready": "Sẵn sàng",
        "popover.updating": "Đang cập nhật",
        "popover.refresh": "Làm mới",
        "popover.lowestQuota": "Quota thấp nhất",
        "popover.loadingQuota": "Đang tải quota",
        "popover.settings": "Cài đặt…",
        "popover.about": "Giới thiệu BirdNion",
        "popover.quit": "Thoát BirdNion",
        "popover.noProviders": "Chưa có nhà cung cấp nào",
        "popover.noProvidersBody": "Mở Settings để chọn nhà cung cấp bạn muốn theo dõi quota AI.",
        "popover.openSettings": "Mở Cài đặt",
        "popover.menuBarVisibility": "Hiển thị trên menu bar",
        "popover.visibilityOn": "Provider này đang hiển thị trên menu bar. Tắt để ẩn.",
        "popover.visibilityOff": "Provider này đang ẩn khỏi menu bar. Bật để hiển thị.",
        "popover.aboutInfo": "Ứng dụng menu bar macOS để theo dõi quota AI.",
        "popover.accounts": "Tài khoản",
        "popover.cliCard.title": "Codex CLI",
        "popover.cliCard.switchTo": "Bấm để chuyển CLI sang %@",
        "popover.restoreCLI": "Bấm để khôi phục CLI về tài khoản gốc",
        "popover.cliAlready": "Tài khoản này đang dùng ở CLI",
        "popover.cliActive": "Đang dùng ở CLI",
        "popover.cliActiveShort": "Đang dùng",
        "popover.accountSelected": "Đã chọn",
        "popover.accountSelectedHelp": "Tài khoản này đang được chọn",
        "popover.switchReady": "Sẵn sàng chuyển",
        "popover.accountQuotaHelp": "Quota thấp nhất: %@ còn %d%%",
        "popover.accountQuotaMissing": "Chưa có dữ liệu quota cho tài khoản này",
        "popover.switchFailed": "Chuyển CLI thất bại: %@",
        "button.close": "Đóng",
        "time.justUpdated": "vừa cập nhật",
        "time.secondsAgo": "%d giây trước",
        "time.minutesAgo": "%d phút trước",
        "time.hoursAgo": "%d giờ trước",
        "quota.used": "Đã dùng %d%%",
        "quota.resetSoon": "Reset sắp tới",
        "quota.resetWeekly": "Reset hằng tuần",
        "quota.resetIn5h": "Reset trong 5h",
        "quota.resetInDaysHours": "Reset trong %dd %dh",
        "quota.resetInHoursMinutes": "Reset trong %dh %dm",
        "quota.resetInMinutes": "Reset trong %dm",
        "notification.quotaBelowThreshold": "Còn %d%% — dưới ngưỡng %d%%",
        "oauth.closeTab": "Bạn có thể đóng tab này.",
        "chart.todayWithDate": "Hôm nay (%@)",
        "chart.today": "Hôm nay",
        "chart.last30Cost": "Chi phí 30 ngày",
        "chart.latestTokens": "Token gần nhất",
        "chart.topModel": "Model nhiều nhất: %@",
        "chart.estimate": "Ước tính từ log Claude cục bộ theo giá API; tổng token là chính xác, USD là gần đúng.",
        "chart.estTotal30": "Tổng ước tính (30 ngày)",
        "config.enter": "Nhập",
        "config.save": "Lưu",
        "config.keyTooLong": "API key quá dài (max 256)",
        "config.saved": "Đã lưu. Khởi động lại Claude Code để áp dụng.",
        "settings.tab.claudeCode": "Claude Code",
        "aiCoding.step.agent": "AI Coding Agent",
        "aiCoding.target": "Agent",
        "aiCoding.agent.claudeCode": "Claude Code",
        "aiCoding.agent.codex": "Codex CLI",
        "aiCoding.claudeCode.settings": "Kích hoạt Claude Code",
        "codexConfig.newName": "Config mới",
        "codexConfig.protocol.responses": "OpenAI Responses",
        "codexConfig.protocol.openaiChat": "OpenAI Chat",
        "codexConfig.protocol.anthropic": "Anthropic",
        "codexConfig.connection": "Kết nối",
        "codexConfig.connection.direct": "API nguồn gốc",
        "codexConfig.connection.proxy": "Proxy local",
        "codexConfig.model": "Model",
        "codexConfig.target": "Kích hoạt Codex CLI",
        "codexConfig.target.path": "~/.codex/config.toml",
        "codexConfig.apply": "Áp dụng cho Codex",
        "codexConfig.update": "Cập nhật Codex",
        "codexConfig.deactivate": "Tắt config",
        "codexConfig.delete": "Xoá config",
        "codexConfig.state.ready": "Sẵn sàng",
        "codexConfig.state.active": "Đang dùng",
        "codexConfig.state.stale": "Cần cập nhật",
        "codexConfig.state.setup": "Cần setup",
        "codexConfig.applied": "Đã áp dụng provider cho Codex CLI.",
        "codexConfig.updated": "Đã cập nhật provider cho Codex CLI.",
        "codexConfig.runWith": "Chạy: `%@` (mặc định toàn cục đã trỏ vào config này; flag chỉ cần khi muốn ghim riêng cho một repo).",
        "codexConfig.deactivated": "Đã trả Codex CLI về config trước đó.",
        "codexConfig.error.incomplete": "Nhập Base URL, API key và model trước.",
        "codexConfig.proxy.running": "Codex CLI có thể dùng endpoint local này.",
        "codexConfig.proxy.stopped": "Khởi động proxy trước khi áp dụng cho Codex CLI.",
        "codexConfig.projectUse.title": "Dùng theo project",
        "codexConfig.projectUse.copy": "Sao chép lệnh",
        "codexConfig.projectUse.hint": "Codex không cho khai provider trong config của project. Chạy lệnh này trong repo muốn dùng config; file ~/.codex/*.config.toml tự cập nhật mỗi lần Áp dụng.",
        "codexConfig.proxy.stopConfirmTitle": "Dừng proxy local?",
        "codexConfig.proxy.stopConfirmMessage": "Codex CLI và Claude Code dùng proxy này sẽ không hoạt động cho đến khi bật lại.",
        "claudeCode.selectProvider": "Chọn provider hoặc config làm backend cho Claude Code / Codex CLI",
        "claudeCode.empty.title": "Chưa có provider nào được nhập API key",
        "claudeCode.empty.body": "Vào tab Nhà cung cấp, nhập API key cho provider bạn muốn dùng làm backend Claude Code, rồi quay lại đây.",
        "claudeCode.empty.openProviders": "Mở tab Nhà cung cấp",
        "claudeCode.scope": "Phạm vi",
        "claudeCode.scope.global": "Toàn cục",
        "claudeCode.scope.project": "Theo project",
        "claudeCode.scope.globalPath": "→ ~/.claude/settings.json",
        "claudeCode.project.choose": "Chọn…",
        "claudeCode.project.none": "Chưa chọn thư mục project",
        "claudeCode.project.gitignore": "Ghi vào .claude/settings.json của project (nhớ gitignore nếu repo chia sẻ để tránh lộ token).",
        "claudeCode.token": "Token",
        "claudeCode.token.using": "Dùng key của %@",
        "claudeCode.baseURL": "Base URL",
        "claudeCode.model": "Model",
        "claudeCode.loadModels": "Tải model",
        "claudeCode.reloadModels": "Tải lại",
        "claudeCode.loadingModels": "Đang tải model…",
        "claudeCode.modelsLoaded": "Đã tải %d model",
        "claudeCode.model.haiku": "Haiku",
        "claudeCode.model.sonnet": "Sonnet",
        "claudeCode.model.opus": "Opus",
        "claudeCode.model.pickPlaceholder": "— chưa tải —",
        "claudeCode.disable1M": "Tắt 1M context",
        "claudeCode.save": "Lưu",
        "claudeCode.saved": "Đã lưu vào %@",
        "claudeCode.applied": "Đã áp dụng cấu hình Claude Code",
        "claudeCode.quickApply.tooltip": "Áp dụng cấu hình Claude Code",
        "claudeCode.quickApply.setup": "Cần cấu hình model — bấm để mở cài đặt",
        "claudeCode.quickCard.title": "Backend Claude Code",
        "claudeCode.quickCard.globalTarget": "Toàn cục · ~/.claude/settings.json",
        "claudeCode.quickCard.projectTarget": "Theo project · %@",
        "claudeCode.quickCard.projectTargetMissing": "Theo project · chưa chọn thư mục",
        "claudeCode.state.on": "Đang bật",
        "claudeCode.state.off": "Sẵn sàng",
        "claudeCode.state.stale": "Cần cập nhật",
        "claudeCode.state.setup": "Cần setup",
        "claudeCode.power.on": "Đang bật · %@",
        "claudeCode.power.off": "Đang tắt — bấm để bật",
        "claudeCode.power.needModels": "Chọn đủ 3 model để bật",
        "claudeCode.power.stale": "Giá trị đã đổi — bấm để cập nhật",
        "claudeCode.updated": "Đã cập nhật giá trị vào settings.json",
        "claudeCode.deactivated": "Đã tắt Claude Code cho provider này",
        "claudeCode.removeEnv.title": "Gỡ env settings",
        "claudeCode.removeEnv.subtitle": "Xoá env/apiKeyHelper trong %@; không xoá token/provider của BirdNion.",
        "claudeCode.removeEnv.button": "Gỡ env",
        "claudeCode.removeEnv.confirmTitle": "Gỡ env Claude Code?",
        "claudeCode.removeEnv.confirmMessage": "BirdNion sẽ xoá env và apiKeyHelper trong %@. Các setting khác vẫn giữ nguyên.",
        "claudeCode.removeEnv.confirmButton": "Gỡ env",
        "claudeCode.removeEnv.done": "Đã gỡ env trong %@",
        "claudeCode.removeEnv.none": "Không có env để gỡ.",
        "ccx.custom": "Tuỳ chỉnh",
        "ccx.add": "Thêm config",
        "ccx.newName": "Config mới",
        "ccx.name": "Tên",
        "ccx.name.placeholder": "Tên hiển thị",
        "ccx.compatibility": "Chuẩn API",
        "ccx.compatibility.hint": "Anthropic = /v1/messages · Chat = /v1/chat/completions · Responses = /v1/responses. Chọn theo docs của provider.",
        "ccx.connection": "Kết nối",
        "ccx.connection.direct": "API nguồn gốc",
        "ccx.connection.proxy": "Proxy local",
        "ccx.tokenEnvKey": "Kiểu key",
        "ccx.token.show": "Hiện token",
        "ccx.token.hide": "Ẩn token",
        "ccx.openai.baseURL": "Base URL",
        "ccx.openai.apiKey": "API key",
        "ccx.proxy.baseURL": "CLIProxyAPI URL",
        "ccx.proxy.apiKey": "Proxy API key",
        "ccx.proxy.managementKey": "Management key",
        "ccx.proxy.localEndpoint": "Local endpoint",
        "ccx.step.upstream": "API nguồn",
        "ccx.step.proxy": "Proxy local",
        "ccx.proxy.start": "Khởi động",
        "ccx.proxy.update": "Cập nhật",
        "ccx.proxy.retry": "Thử lại",
        "ccx.proxy.refresh": "Làm mới trạng thái",
        "ccx.proxy.copyEndpoint": "Sao chép endpoint",
        "ccx.proxy.started": "Proxy local đã sẵn sàng.",
        "ccx.proxy.stop": "Dừng proxy local",
        "ccx.proxy.stop.confirmTitle": "Dừng proxy local?",
        "ccx.proxy.stop.confirmMessage": "Claude Code và Codex CLI dùng proxy này sẽ không hoạt động cho đến khi bật lại.",
        "ccx.proxy.stop.done": "Đã dừng proxy local.",
        "ccx.proxy.stop.none": "Không có proxy local đang chạy.",
        "ccx.proxy.error.incomplete": "Thiếu Base URL hoặc API key",
        "ccx.proxy.error.helperUnavailable": "Không tìm thấy core CLIProxyAPI trong ứng dụng",
        "ccx.proxy.error.didNotStart": "Không khởi động được proxy local",
        "ccx.proxy.error.invalidURL": "Local proxy URL không hợp lệ",
        "ccx.proxy.error.network": "Không kết nối được proxy local",
        "ccx.proxy.error.http": "CLIProxyAPI trả về HTTP %@",
        "ccx.proxy.error.invalidResponse": "CLIProxyAPI trả về dữ liệu không hợp lệ",
        "ccx.proxy.tapToStart": "Proxy local chưa chạy — nút nguồn sẽ tự khởi động proxy rồi áp dụng.",
        "ccx.proxy.status.needsConfig": "Cần thông tin API nguồn",
        "ccx.proxy.status.checking": "Đang kiểm tra proxy local",
        "ccx.proxy.status.starting": "Đang khởi động proxy local",
        "ccx.proxy.status.running": "Proxy local đang chạy",
        "ccx.proxy.status.needsUpdate": "Profile cần cập nhật proxy",
        "ccx.proxy.status.stopped": "Proxy local đang dừng",
        "ccx.proxy.status.failed": "Proxy local cần xử lý",
        "ccx.proxy.detail.needsConfig": "Nhập Base URL và API key trước khi khởi động.",
        "ccx.proxy.detail.checking": "Đang kiểm tra endpoint trên máy này.",
        "ccx.proxy.detail.starting": "Đang chờ CLIProxyAPI sẵn sàng.",
        "ccx.proxy.detail.running": "Claude Code có thể dùng endpoint local này.",
        "ccx.proxy.detail.needsUpdate": "Proxy đang chạy nhưng chưa nạp thay đổi của profile này.",
        "ccx.proxy.detail.stopped": "Khởi động proxy trước khi áp dụng cho Claude Code.",
        "ccx.proxy.detail.failed": "Kiểm tra API nguồn rồi thử lại.",
        "ccx.model.optional": "Tuỳ chọn",
        "ccx.advanced": "Nâng cao",
        "ccx.apiKeyHelper.placeholder": "vd: echo 'sk-...' (tuỳ chọn)",
        "ccx.extraEnv": "Env tuỳ chỉnh",
        "ccx.extraEnv.add": "Thêm env",
        "ccx.delete": "Xoá config",
        "ccx.delete.confirmTitle": "Xoá config này?",
        "ccx.delete.confirmMessage": "\"%@\" cùng API key đã lưu sẽ bị xoá vĩnh viễn.",
        "ccx.needConfig": "Nhập Base URL + Token để bật",
        "ccx.needProxyConfig": "Nhập Base URL + API key để bật",
        "ccx.savedProfile": "Đã lưu config",
        "ccx.pasteJSON": "Dán JSON",
        "ccx.pasteJSON.title": "Dán JSON cấu hình Claude Code",
        "ccx.pasteJSON.hint": "Dán cả khối settings.json (có \"env\") hoặc chỉ khối env. App sẽ tự tách field.",
        "ccx.pasteJSON.apply": "Nhập",
        "ccx.pasteJSON.cancel": "Huỷ",
        "ccx.pasteJSON.imported": "Đã nhập từ JSON",
    ]

    private static let en: [String: String] = [
        "language.system": "System",
        "language.english": "English",
        "language.vietnamese": "Vietnamese",
        "settings.tab.general": "General",
        "settings.tab.providers": "Providers",
        "settings.tab.display": "Display",
        "settings.tab.advanced": "Advanced",
        "settings.tab.about": "About",
        "settings.tab.debug": "Debug",
        "settings.tab.codex": "Codex",
        "settings.tab.aiCoding": "AI Coding",
        "settings.section.system": "System",
        "settings.section.usage": "Usage",
        "settings.section.automation": "Automation",
        "settings.section.privacy": "Privacy",
        "settings.section.developer": "Developer",
        "settings.section.files": "Files",
        "settings.section.menuBar": "Menu Bar",
        "settings.section.links": "Links",
        "settings.section.setup": "Setup",
        "settings.section.account": "Accounts",
        "settings.codex.autoPrime.title": "Auto-Prime 5h Window",
        "settings.codex.autoPrime.toggle": "Auto-prime",
        "settings.codex.autoPrime.toggleSubtitle": "Sends one small request daily to start the 5h clock at your working hours.",
        "settings.codex.autoPrime.time": "Prime time",
        "settings.codex.autoPrime.timeSubtitle": "Only primes while the 5h window is idle (not yet used).",
        "notification.codexPrimed.title": "Codex 5h window primed",
        "notification.codexPrimed.body": "The 5h window was activated at %@.",
        "settings.section.quotaWarnings": "Quota Warnings",
        "settings.refresh.manual": "Manual",
        "settings.manualRefreshHint": "Automatic refresh is off — use the refresh button in the popover.",
        "settings.refreshOnOpen.title": "Refresh when opening",
        "settings.refreshOnOpen.subtitle": "Refresh all providers each time the popover opens.",
        "settings.quitApp": "Quit BirdNion",
        "settings.warningSound.title": "Play sound",
        "settings.warningSound.subtitle": "Play a sound with quota warnings.",
        "settings.warningAlert.title": "On-screen alert",
        "settings.warningAlert.subtitle": "Show a brief centered alert when a threshold is crossed.",
        "settings.section.shortcut": "Keyboard Shortcut",
        "settings.hotkey.title": "Open popover",
        "settings.hotkey.subtitle": "Global shortcut to toggle the quota popover.",
        "settings.disableKeychain.title": "Disable Keychain access",
        "settings.disableKeychain.subtitle": "Debug: skip macOS Keychain reads (Claude OAuth, browser cookies).",
        "settings.storageFootprint.title": "Show provider storage usage",
        "settings.storageFootprint.subtitle": "Show each provider's on-disk data size in Providers.",
        "provider.storage": "Storage",
        "provider.storage.none": "No local data",
        "about.section.updates": "Updates",
        "about.autoCheck.title": "Check automatically",
        "about.autoCheck.subtitle": "Check for new releases once a day at launch.",
        "about.channel.title": "Update channel",
        "about.channel.stable": "Stable",
        "about.channel.beta": "Beta",
        "about.checkNow": "Check for updates",
        "about.checking": "Checking…",
        "about.upToDate": "You're up to date.",
        "about.updateAvailable": "Version %@ available",
        "about.openRelease": "View release",
        "about.updateNow": "Update now",
        "about.checkFailed": "Could not check for updates.",
        "about.buildDate": "Built %@",
        "providerError.cookieExpiredOrMissing.title": "Cookie expired",
        "providerError.cookieExpiredOrMissing.hint": "Cookie expired — sign in again in your browser",
        "providerError.tokenInvalidOrMissing.title": "Invalid token",
        "providerError.tokenInvalidOrMissing.hint": "Invalid token — re-paste your API key",
        "providerError.apiSchemaChanged.title": "Unexpected response",
        "providerError.apiSchemaChanged.hint": "Unexpected response — the app may need an update",
        "providerError.networkUnreachableOrTimeout.title": "Network error",
        "providerError.networkUnreachableOrTimeout.hint": "Network down or timed out — check your connection",
        "providerError.rateLimited.title": "Rate limited",
        "providerError.rateLimited.hint": "Rate limited — wait and retry",
        "providerError.unknown.title": "Unknown error",
        "providerError.unknown.hint": "Unknown error — see details",
        "provider.selfTest": "Self-test",
        "provider.selfTest.running": "Testing…",
        "provider.selfTest.pass": "Passed",
        "provider.selfTest.fail": "Failed",
        "provider.selfTest.disabled": "Enable the provider to test",
        "notification.providerFailing": "%@ — %@",
        "settings.language.title": "Language",
        "settings.language.subtitle": "Updates the UI immediately and persists for the next launch.",
        "settings.launchAtLogin.title": "Launch at login",
        "settings.launchAtLogin.subtitle": "Open BirdNion automatically when you sign in.",
        "settings.refreshFrequency.title": "Refresh frequency",
        "settings.refreshFrequency.subtitle": "How often BirdNion calls each provider.",
        "settings.statusChecks.title": "Status checks",
        "settings.statusChecks.subtitle": "Poll provider status pages.",
        "settings.sessionNotifications.title": "5-hour session notifications",
        "settings.sessionNotifications.subtitle": "Notify when session quota reaches 0% and recovers.",
        "settings.quotaWarningNotifications.title": "Quota warning notifications",
        "settings.quotaWarningNotifications.subtitle": "Warn when remaining quota falls below your thresholds.",
        "settings.warningThreshold.title": "Warning threshold",
        "settings.warningThreshold.subtitle": "First warning when remaining % reaches this level.",
        "settings.criticalThreshold.title": "Critical threshold",
        "settings.criticalThreshold.subtitle": "Second warning at a lower remaining level.",
        "settings.hidePersonalInfo.title": "Hide personal info",
        "settings.hidePersonalInfo.subtitle": "Mask account email on chips and in the popover.",
        "settings.debugMenu.title": "Show Debug tab",
        "settings.debugMenu.subtitle": "Adds a Debug tab for logs and cache shortcuts.",
        "settings.developer.footer": "Some technical changes may still require reopening the app.",
        "settings.display.footer": "When off, the menu bar shows only the BirdNion logo.",
        "settings.showPercentInMenuBar.title": "Show percent in menu bar",
        "settings.showPercentInMenuBar.subtitle": "Rotates through active provider quotas; falls back to the bird logo when no data is active.",
        "settings.mergeIcons.title": "Merge provider icons",
        "settings.mergeIcons.subtitle": "Legacy setting; the menu bar now uses the percent option above.",
        "settings.switcherShowsIcons.title": "Switcher shows icons",
        "settings.switcherShowsIcons.subtitle.on": "Show icons when switching providers from the popover.",
        "settings.switcherShowsIcons.subtitle.off": "Enable “Merge provider icons” first.",
        "settings.debug.footer": "For real probe/fetch-strategy logs, open Console.app and filter by bundle ID.",
        "settings.configFile.title": "Config file",
        "settings.openFinder": "Open Finder",
        "about.openProject": "Open the project page on GitHub",
        "about.tagline": "Track AI quota from your menu bar.",
        "about.version": "version %@ (%@)",
        "provider.search": "Search providers",
        "provider.clearSearch": "Clear",
        "provider.reorderHelp": "Drag to reorder providers",
        "provider.choose": "Choose a provider",
        "provider.enableHelp.on": "Disable polling for this provider",
        "provider.enableHelp.off": "Enable polling for this provider",
        "provider.disabled": "Disabled",
        "provider.notLoaded": "Not loaded",
        "provider.loading": "Loading…",
        "provider.error": "Error",
        "provider.errorPrefix": "Error: %@",
        "provider.remaining": "%d%% left",
        "provider.status": "Status",
        "provider.source": "Source",
        "provider.plan": "Plan",
        "provider.planName": "Plan name",
        "provider.account": "Account",
        "provider.version": "Version",
        "provider.kiroContext": "Context window",
        "provider.serviceStatus": "Service status",
        "provider.resetCredits": "Resets available",
        "provider.codeReview": "Code review",
        "provider.creditsHistory": "Credits history",
        "provider.buyCredits": "Buy credits",
        "provider.openPage": "Open page",
        "provider.updated": "Updated",
        "provider.reloadHelp": "Reload settings.json and refresh quota",
        "provider.noData.enabled": "No data yet — click refresh.",
        "provider.noData.disabled": "Disabled — no data.",
        "provider.reserve": "%d%% reserve",
        "provider.resetAfter": "Resets in %@",
        "provider.enoughUntilReset": "Enough until reset",
        "provider.mayRunOut": "May run out before reset",
        "provider.credits": "CREDITS",
        "provider.creditsAvailable": "Credits available",
        "provider.unlimited": "∞ Unlimited",
        "provider.creditsLeft": "%@ left",
        "provider.outOfCredits": "Empty",
        "provider.cost": "COST",
        "provider.usedRemaining": "%d%% used · %@ left",
        "provider.today": "Today",
        "provider.last30": "30 days",
        "provider.email": "EMAIL",
        "provider.organization": "ORG",
        "provider.login": "LOGIN",
        "provider.accountLabel": "Account label",
        "provider.accountLabelPlaceholder": "Optional — leave blank to infer",
        "provider.signIn": "Sign in",
        "provider.codexSignInHint": "Sign in with `codex` in Terminal.",
        "provider.dataSource": "Data source",
        "provider.menuBarMetric": "Menu bar metric",
        "provider.apiRegion": "API region",
        "provider.refreshEvery": "Refresh every",
        "provider.defaultGlobal": "Default = general setting (%@)",
        "provider.cookie": "Cookie",
        "provider.cookiePlaceholder": "Paste Cookie: header from chatgpt.com",
        "provider.cookieClaude": "Claude cookie",
        "provider.manualCookie": "Manual Cookie header",
        "provider.manualCookieHelp": "Open claude.ai in a signed-in browser → DevTools → Network → copy the full `Cookie:` header.",
        "provider.keychainOAuth": "Keychain OAuth",
        "provider.openAIWebExtras": "OpenAI web extras",
        "provider.openAIWebExtrasHelp": "Scan chatgpt.com in a hidden WebView for code-review %, credits, and history. Uses more battery/network — off by default.",
        "provider.claudeConfig": "Claude config…",
        "provider.token": "Token",
        "provider.tokenPlaceholder": "Paste token here",
        "provider.save": "Save",
        "provider.savedSettings": "Saved to ~/.config/birdnion/settings.json.",
        "provider.saveError": "Save failed: %@",
        "provider.quotaWarningsFooter": "Uses global thresholds unless you enable custom thresholds for each window.",
        "provider.sessionWindow": "Session (5 hours)",
        "provider.weekWindow": "Week",
        "provider.customThresholds": "Customize %@ thresholds",
        "provider.inherited": "Inherited: %@",
        "provider.warning": "Warning",
        "provider.critical": "Critical",
        "provider.accountsFooter": "Each account signs in separately. “Add account” opens `codex login` in the browser; the system account (~/.codex) is left untouched.",
        "provider.systemAccount": "System account",
        "provider.accountGeneric": "Account",
        "freemodel.browserAuto": "Browser (auto)",
        "freemodel.switchAccount": "Switch to this account",
        "freemodel.addAccount": "Add",
        "freemodel.addHint": "Paste a bm_session cookie from a browser signed in to freemodel.dev (DevTools → Application → Cookies). Signed-in browsers are auto-detected above.",
        "freemodel.cookiePlaceholder": "bm_session=… or the full Cookie string",
        "freemodel.labelPlaceholder": "Label (optional)",
        "freemodel.cookieNeedsSession": "Cookie must contain bm_session",
        "elevenlabs.keysLabel": "ElevenLabs API keys",
        "elevenlabs.keysFooter": "Store multiple API keys and switch from the popover. Keys live in a separate file (not mixed into shared settings).",
        "elevenlabs.keysEmpty": "No API keys yet — paste a key below to add one.",
        "elevenlabs.keyPlaceholder": "Paste ElevenLabs API key…",
        "elevenlabs.labelPlaceholder": "Label (optional)",
        "elevenlabs.addKey": "Add key",
        "elevenlabs.switchKey": "Use this key",
        "elevenlabs.activeBadge": "Active",
        "elevenlabs.popoverTitle": "API keys",
        "provider.systemManaged": "System · ~/.codex",
        "provider.appManaged": "Managed by app",
        "provider.reauth": "Sign in again",
        "provider.saveManaged": "Save as managed",
        "provider.addAccount": "Add account",
        "provider.waitingLogin": "Waiting for browser sign-in…",
        "provider.addAccountFailed": "Add account failed: %@",
        "provider.removeAccount": "Remove account",
        "provider.removeSystemAccount": "Remove system login",
        "provider.removeAccountTitle": "Remove %@?",
        "provider.removeAccountMessage": "The managed account will be removed from BirdNion.",
        "provider.removeSystemAccountMessage": "The ~/.codex/auth.json file will be moved to a backup so you can sign in again.",
        "provider.removeAccountFailed": "Remove account failed: %@",
        "provider.link.codexUsage": "Codex usage page",
        "provider.link.openAIStatus": "OpenAI status",
        "provider.link.changelog": "Changelog",
        "provider.link.minimaxPlan": "Token Plan page",
        "provider.link.openRouterCredits": "OpenRouter credits",
        "provider.link.apiKeys": "API keys",
        "provider.link.deepSeekBalance": "DeepSeek balance",
        "provider.link.codingPlan": "Coding Plan",
        "provider.link.anthropicStatus": "Anthropic status",
        "provider.link.dashboard": "Dashboard",
        "provider.link.status": "Service status",
        "provider.link.usage": "Usage page",
        "provider.link.subscription": "Subscription",
        "provider.link.billing": "Billing",
        "source.auto": "Auto",
        "source.oauth": "OAuth",
        "source.cli": "CLI",
        "source.codex.auto.subtitle": "OAuth, falling back to `codex app-server` CLI on errors (default).",
        "source.codex.oauth.subtitle": "OAuth only (~/.codex/auth.json token) — no CLI fallback.",
        "source.codex.cli.subtitle": "Only local `codex app-server` RPC — skips OAuth.",
        "source.claude.auto.subtitle": "Try OAuth → Web → CLI and use the first successful source.",
        "source.claude.oauth.subtitle": "Use the OAuth token in Claude Code Keychain (default).",
        "source.claude.web.subtitle": "Scrape claude.ai with Safari/Chrome cookies.",
        "source.claude.cli.subtitle": "Run the `claude` CLI in a PTY (requires CLI installed).",
        "source.claude.api.subtitle": "Anthropic Admin API (requires an admin key below).",
        "metric.automatic": "Automatic",
        "metric.session": "Session (5 hours)",
        "metric.weekly": "Week",
        "region.china": "China (platform.minimaxi.com)",
        "prompt.never": "Never",
        "prompt.onlyOnUserAction": "Only on click",
        "prompt.always": "Always ask",
        "refresh.default": "General default",
        "refresh.30s": "30 seconds",
        "refresh.1m": "1 minute",
        "refresh.2m": "2 minutes",
        "refresh.5m": "5 minutes",
        "refresh.10m": "10 minutes",
        "refresh.30m": "30 minutes",
        "popover.ready": "Ready",
        "popover.updating": "Updating",
        "popover.refresh": "Refresh",
        "popover.lowestQuota": "Lowest quota",
        "popover.loadingQuota": "Loading quota",
        "popover.settings": "Settings…",
        "popover.about": "About BirdNion",
        "popover.quit": "Quit BirdNion",
        "popover.noProviders": "No providers enabled",
        "popover.noProvidersBody": "Open Settings to choose which AI quota providers to track.",
        "popover.openSettings": "Open Settings",
        "popover.menuBarVisibility": "Menu bar visibility",
        "popover.visibilityOn": "This provider is visible in the menu bar. Turn off to hide it.",
        "popover.visibilityOff": "This provider is hidden from the menu bar. Turn on to show it.",
        "popover.aboutInfo": "macOS menu bar app for tracking AI provider quota.",
        "popover.accounts": "Accounts",
        "popover.cliCard.title": "Codex CLI",
        "popover.cliCard.switchTo": "Tap to switch the CLI to %@",
        "popover.restoreCLI": "Tap to restore the original CLI login",
        "popover.cliAlready": "This account is active in the CLI",
        "popover.cliActive": "In CLI",
        "popover.cliActiveShort": "Active",
        "popover.accountSelected": "Selected",
        "popover.accountSelectedHelp": "This account is selected",
        "popover.switchReady": "Ready to switch",
        "popover.accountQuotaHelp": "Lowest quota: %@ has %d%% remaining",
        "popover.accountQuotaMissing": "No quota data has been cached for this account yet",
        "popover.switchFailed": "Switch CLI failed: %@",
        "button.close": "Close",
        "time.justUpdated": "just updated",
        "time.secondsAgo": "%d seconds ago",
        "time.minutesAgo": "%d minutes ago",
        "time.hoursAgo": "%d hours ago",
        "quota.used": "Used %d%%",
        "quota.resetSoon": "Reset soon",
        "quota.resetWeekly": "Resets weekly",
        "quota.resetIn5h": "Resets in 5h",
        "quota.resetInDaysHours": "Resets in %dd %dh",
        "quota.resetInHoursMinutes": "Resets in %dh %dm",
        "quota.resetInMinutes": "Resets in %dm",
        "notification.quotaBelowThreshold": "%d%% left — below the %d%% threshold",
        "oauth.closeTab": "You can close this tab.",
        "chart.todayWithDate": "Today (%@)",
        "chart.today": "Today",
        "chart.last30Cost": "30d cost",
        "chart.latestTokens": "Latest tokens",
        "chart.topModel": "Top model: %@",
        "chart.estimate": "Estimated from local Claude logs at API rates; token totals are exact, USD are approximate.",
        "chart.estTotal30": "Est. total (Last 30 days)",
        "config.enter": "Enter",
        "config.save": "Save",
        "config.keyTooLong": "API key is too long (max 256)",
        "config.saved": "Saved. Restart Claude Code to apply.",
        "settings.tab.claudeCode": "Claude Code",
        "aiCoding.step.agent": "AI Coding Agent",
        "aiCoding.target": "Agent",
        "aiCoding.agent.claudeCode": "Claude Code",
        "aiCoding.agent.codex": "Codex CLI",
        "aiCoding.claudeCode.settings": "Activate Claude Code",
        "codexConfig.newName": "New config",
        "codexConfig.protocol.responses": "OpenAI Responses",
        "codexConfig.protocol.openaiChat": "OpenAI Chat",
        "codexConfig.protocol.anthropic": "Anthropic",
        "codexConfig.connection": "Connection",
        "codexConfig.connection.direct": "Original upstream",
        "codexConfig.connection.proxy": "Local proxy",
        "codexConfig.model": "Model",
        "codexConfig.target": "Activate Codex CLI",
        "codexConfig.target.path": "~/.codex/config.toml",
        "codexConfig.apply": "Apply to Codex",
        "codexConfig.update": "Update Codex",
        "codexConfig.deactivate": "Disable config",
        "codexConfig.delete": "Delete config",
        "codexConfig.state.ready": "Ready",
        "codexConfig.state.active": "Active",
        "codexConfig.state.stale": "Needs update",
        "codexConfig.state.setup": "Setup",
        "codexConfig.applied": "Provider applied to Codex CLI.",
        "codexConfig.updated": "Provider updated for Codex CLI.",
        "codexConfig.runWith": "Run: `%@` (the global default already points at this config; the flag is only needed to pin a specific repo).",
        "codexConfig.deactivated": "Codex CLI restored to its previous config.",
        "codexConfig.error.incomplete": "Enter the Base URL, API key, and model first.",
        "codexConfig.proxy.running": "Codex CLI can use this local endpoint.",
        "codexConfig.proxy.stopped": "Start the proxy before applying it to Codex CLI.",
        "codexConfig.projectUse.title": "Per-project use",
        "codexConfig.projectUse.copy": "Copy command",
        "codexConfig.projectUse.hint": "Codex ignores provider keys in project-local config. Run this command inside the repo that should use this config; the ~/.codex/*.config.toml overlay refreshes on every Apply.",
        "codexConfig.proxy.stopConfirmTitle": "Stop local proxy?",
        "codexConfig.proxy.stopConfirmMessage": "Codex CLI and Claude Code profiles using this proxy cannot work until you enable it again.",
        "claudeCode.selectProvider": "Pick a provider or config to back Claude Code / Codex CLI",
        "claudeCode.empty.title": "No provider has an API key yet",
        "claudeCode.empty.body": "Go to the Providers tab, enter an API key for the provider you want to use as the Claude Code backend, then come back here.",
        "claudeCode.empty.openProviders": "Open Providers tab",
        "claudeCode.scope": "Scope",
        "claudeCode.scope.global": "Global",
        "claudeCode.scope.project": "Per project",
        "claudeCode.scope.globalPath": "→ ~/.claude/settings.json",
        "claudeCode.project.choose": "Choose…",
        "claudeCode.project.none": "No project folder chosen",
        "claudeCode.project.gitignore": "Writes to the project's .claude/settings.json (git-ignore it if the repo is shared to avoid leaking the token).",
        "claudeCode.token": "Token",
        "claudeCode.token.using": "Using %@'s key",
        "claudeCode.baseURL": "Base URL",
        "claudeCode.model": "Model",
        "claudeCode.loadModels": "Load models",
        "claudeCode.reloadModels": "Reload",
        "claudeCode.loadingModels": "Loading models…",
        "claudeCode.modelsLoaded": "Loaded %d models",
        "claudeCode.model.haiku": "Haiku",
        "claudeCode.model.sonnet": "Sonnet",
        "claudeCode.model.opus": "Opus",
        "claudeCode.model.pickPlaceholder": "— not loaded —",
        "claudeCode.disable1M": "Disable 1M context",
        "claudeCode.save": "Save",
        "claudeCode.saved": "Saved to %@",
        "claudeCode.applied": "Claude Code config applied",
        "claudeCode.quickApply.tooltip": "Apply Claude Code config",
        "claudeCode.quickApply.setup": "Model setup needed — click to open settings",
        "claudeCode.quickCard.title": "Claude Code backend",
        "claudeCode.quickCard.globalTarget": "Global · ~/.claude/settings.json",
        "claudeCode.quickCard.projectTarget": "Per project · %@",
        "claudeCode.quickCard.projectTargetMissing": "Per project · no folder chosen",
        "claudeCode.state.on": "On",
        "claudeCode.state.off": "Ready",
        "claudeCode.state.stale": "Update",
        "claudeCode.state.setup": "Setup",
        "claudeCode.power.on": "On · %@",
        "claudeCode.power.off": "Off — tap to enable",
        "claudeCode.power.needModels": "Pick 3 models to enable",
        "claudeCode.power.stale": "Values changed — tap to update",
        "claudeCode.updated": "Updated values in settings.json",
        "claudeCode.deactivated": "Claude Code disabled for this provider",
        "claudeCode.removeEnv.title": "Remove env settings",
        "claudeCode.removeEnv.subtitle": "Removes env/apiKeyHelper from %@; BirdNion provider tokens stay saved.",
        "claudeCode.removeEnv.button": "Remove env",
        "claudeCode.removeEnv.confirmTitle": "Remove Claude Code env?",
        "claudeCode.removeEnv.confirmMessage": "BirdNion will remove env and apiKeyHelper from %@. Other settings stay intact.",
        "claudeCode.removeEnv.confirmButton": "Remove env",
        "claudeCode.removeEnv.done": "Removed env from %@",
        "claudeCode.removeEnv.none": "No env settings to remove.",
        "ccx.custom": "Custom",
        "ccx.add": "Add config",
        "ccx.newName": "New config",
        "ccx.name": "Name",
        "ccx.name.placeholder": "Display name",
        "ccx.compatibility": "API standard",
        "ccx.compatibility.hint": "Anthropic = /v1/messages · Chat = /v1/chat/completions · Responses = /v1/responses. Pick per your provider's docs.",
        "ccx.connection": "Connection",
        "ccx.connection.direct": "Original upstream",
        "ccx.connection.proxy": "Local proxy",
        "ccx.tokenEnvKey": "Token env key",
        "ccx.token.show": "Show token",
        "ccx.token.hide": "Hide token",
        "ccx.openai.baseURL": "Base URL",
        "ccx.openai.apiKey": "API key",
        "ccx.proxy.baseURL": "CLIProxyAPI URL",
        "ccx.proxy.apiKey": "Proxy API key",
        "ccx.proxy.managementKey": "Management key",
        "ccx.proxy.localEndpoint": "Local endpoint",
        "ccx.step.upstream": "Upstream API",
        "ccx.step.proxy": "Local proxy",
        "ccx.proxy.start": "Start",
        "ccx.proxy.update": "Update",
        "ccx.proxy.retry": "Retry",
        "ccx.proxy.refresh": "Refresh status",
        "ccx.proxy.copyEndpoint": "Copy endpoint",
        "ccx.proxy.started": "Local proxy is ready.",
        "ccx.proxy.stop": "Stop local proxy",
        "ccx.proxy.stop.confirmTitle": "Stop local proxy?",
        "ccx.proxy.stop.confirmMessage": "Claude Code and Codex CLI profiles using this proxy cannot work until you enable it again.",
        "ccx.proxy.stop.done": "Local proxy stopped.",
        "ccx.proxy.stop.none": "No local proxy is running.",
        "ccx.proxy.error.incomplete": "Base URL or API key is missing",
        "ccx.proxy.error.helperUnavailable": "CLIProxyAPI core is missing from the app",
        "ccx.proxy.error.didNotStart": "Could not start the local proxy",
        "ccx.proxy.error.invalidURL": "Local proxy URL is invalid",
        "ccx.proxy.error.network": "Could not connect to the local proxy",
        "ccx.proxy.error.http": "CLIProxyAPI returned HTTP %@",
        "ccx.proxy.error.invalidResponse": "CLIProxyAPI returned invalid data",
        "ccx.proxy.tapToStart": "The local proxy isn't running — the power button will start it and apply.",
        "ccx.proxy.status.needsConfig": "Upstream API details needed",
        "ccx.proxy.status.checking": "Checking local proxy",
        "ccx.proxy.status.starting": "Starting local proxy",
        "ccx.proxy.status.running": "Local proxy is running",
        "ccx.proxy.status.needsUpdate": "Profile needs a proxy update",
        "ccx.proxy.status.stopped": "Local proxy is stopped",
        "ccx.proxy.status.failed": "Local proxy needs attention",
        "ccx.proxy.detail.needsConfig": "Enter the Base URL and API key before starting.",
        "ccx.proxy.detail.checking": "Checking the endpoint on this Mac.",
        "ccx.proxy.detail.starting": "Waiting for CLIProxyAPI to become ready.",
        "ccx.proxy.detail.running": "Claude Code can use this local endpoint.",
        "ccx.proxy.detail.needsUpdate": "The proxy is running but has not loaded this profile's changes.",
        "ccx.proxy.detail.stopped": "Start the proxy before applying it to Claude Code.",
        "ccx.proxy.detail.failed": "Check the upstream API and try again.",
        "ccx.model.optional": "Optional",
        "ccx.advanced": "Advanced",
        "ccx.apiKeyHelper.placeholder": "e.g. echo 'sk-...' (optional)",
        "ccx.extraEnv": "Custom env",
        "ccx.extraEnv.add": "Add env",
        "ccx.delete": "Delete config",
        "ccx.delete.confirmTitle": "Delete this config?",
        "ccx.delete.confirmMessage": "\"%@\" and its saved API key will be permanently deleted.",
        "ccx.needConfig": "Enter base URL + token to enable",
        "ccx.needProxyConfig": "Enter base URL + API key to enable",
        "ccx.savedProfile": "Config saved",
        "ccx.pasteJSON": "Paste JSON",
        "ccx.pasteJSON.title": "Paste Claude Code config JSON",
        "ccx.pasteJSON.hint": "Paste a full settings.json (with \"env\") or just the env block. Fields are extracted automatically.",
        "ccx.pasteJSON.apply": "Import",
        "ccx.pasteJSON.cancel": "Cancel",
        "ccx.pasteJSON.imported": "Imported from JSON",
    ]
}
