import Combine
import Foundation
import Security

/// Owns the bundled CLIProxyAPI core used by custom Claude Code profiles. The
/// helper only binds loopback, and both its API and management credentials are
/// generated by BirdNion rather than entered through the UI.
@MainActor
final class EmbeddedCLIProxyService: ObservableObject {
    enum ServiceError: Error, Equatable {
        case incompleteConfiguration
        case helperUnavailable
        case didNotStart
    }

    static let shared = EmbeddedCLIProxyService()
    static let localEndpoint = CLIProxyAPIConfiguration.localBaseURL + "/v1"

    @Published private(set) var runtimeState: LocalProxyRuntimeState = .checking

    private let processController = LocalProxyProcessController()

    private init() {}

    func prepare(profile: BirdNionConfigStore.ClaudeCodeProfile) async throws
    -> BirdNionConfigStore.ClaudeCodeProfile {
        guard profile.hasUpstreamConfiguration else { throw ServiceError.incompleteConfiguration }
        runtimeState = .starting
        do {
            let prepared = try prepareProfile(replacing: profile)
            try await reload(profiles: [prepared])

            var applied = prepared
            applied.cliProxyAppliedSignature = applied.cliProxyConfigurationSignature
            try BirdNionConfigStore.saveClaudeCodeProfile(applied)
            runtimeState = .running
            return applied
        } catch {
            runtimeState = .failed
            throw error
        }
    }

    /// Starts the local helper after app launch when a previously activated
    /// profile exists. Failures stay non-blocking because Settings can surface
    /// the precise error during the next explicit apply.
    func restoreIfConfigured() async {
        var profiles = BirdNionConfigStore.claudeCodeProfiles()
        guard profiles.contains(where: { $0.embeddedLocalProxy == true && $0.isEmbeddedCLIProxyReady }) else {
            runtimeState = .stopped
            return
        }
        do {
            if try migrateProfilesToCurrentPort(&profiles) {
                runtimeState = .stopped
                return
            }
            let activeProfiles = Self.activeProfiles(from: profiles)
            guard activeProfiles.count == 1 else {
                runtimeState = .stopped
                return
            }
            runtimeState = .starting
            try await reload(profiles: activeProfiles)
            runtimeState = .running
        } catch {
            runtimeState = .failed
            NSLog("BirdNion local proxy restore failed: %@", error.localizedDescription)
        }
    }

    /// Removes deleted profiles' upstream credentials and local API keys from
    /// the running helper immediately. No remaining embedded profile means the
    /// helper is no longer needed.
    func reconcileStoredProfiles() async {
        let profiles = BirdNionConfigStore.claudeCodeProfiles()
        let activeProfiles = Self.activeProfiles(from: profiles)
        guard activeProfiles.count == 1 else {
            stop()
            runtimeState = .stopped
            return
        }
        do {
            runtimeState = .starting
            try await reload(profiles: activeProfiles)
            runtimeState = .running
        } catch {
            runtimeState = .failed
            NSLog("BirdNion local proxy reconciliation failed: %@", error.localizedDescription)
        }
    }

    @discardableResult
    func stop() -> Bool {
        let stopped = processController.stopOwnedProcess()
        if stopped { runtimeState = .stopped }
        return stopped
    }

    /// User-initiated teardown. Besides the helper owned by this app instance,
    /// this removes an older BirdNion helper that still listens on either port.
    @discardableResult
    func stopManagedLocalProxy() -> Bool {
        let stopped = processController.stopManagedListeners(
            configURL: configURL,
            ports: [CLIProxyAPIConfiguration.localPort, CLIProxyAPIConfiguration.legacyLocalPort]
        )
        runtimeState = .stopped
        return stopped
    }

    /// A direct Anthropic-compatible profile replaces the loopback endpoint in
    /// Claude Code. Clear any old proxy activation markers before stopping the
    /// helper so the profile list never reports a stale proxy as active.
    func deactivateForDirectUpstream() {
        for profile in BirdNionConfigStore.claudeCodeProfiles() where profile.cliProxyAppliedSignature != nil {
            var updated = profile
            updated.cliProxyAppliedSignature = nil
            try? BirdNionConfigStore.saveClaudeCodeProfile(updated)
        }
        _ = stopManagedLocalProxy()
    }

    static func isProfileRunning(_ profile: BirdNionConfigStore.ClaudeCodeProfile,
                                 runtimeState: LocalProxyRuntimeState) -> Bool {
        profile.usesEmbeddedCLIProxy
            && profile.isCLIProxyConfigurationCurrent
            && runtimeState == .running
    }

    /// Refreshes the observable state when the Settings pane opens, without
    /// starting a helper or mutating the user's Claude Code configuration.
    func refreshRuntimeStatus() async {
        guard runtimeState != .starting else { return }
        runtimeState = .checking
        runtimeState = await isHealthy() ? .running : .stopped
    }

    static func needsLocalPortMigration(_ profile: BirdNionConfigStore.ClaudeCodeProfile) -> Bool {
        profile.embeddedLocalProxy == true
            && profile.isEmbeddedCLIProxyReady
            && profile.normalizedCLIProxyBaseURL != CLIProxyAPIConfiguration.localBaseURL
    }

    private func prepareProfile(replacing profile: BirdNionConfigStore.ClaudeCodeProfile) throws
    -> BirdNionConfigStore.ClaudeCodeProfile {
        var profiles = BirdNionConfigStore.claudeCodeProfiles()
        if let index = profiles.firstIndex(where: { $0.id == profile.id }) {
            profiles[index] = profile
        } else {
            profiles.append(profile)
        }

        let sharedManagementKey = profiles.compactMap { candidate -> String? in
            guard candidate.embeddedLocalProxy == true else { return nil }
            return cleaned(candidate.cliProxyManagementKey)
        }.first ?? randomSecret()

        for index in profiles.indices {
            let previous = profiles[index]
            if profiles[index].id == profile.id {
                let needsFreshLocalKey = previous.embeddedLocalProxy != true || cleaned(previous.cliProxyAPIKey) == nil
                profiles[index].embeddedLocalProxy = true
                profiles[index].cliProxyBaseURL = CLIProxyAPIConfiguration.localBaseURL
                profiles[index].cliProxyAPIKey = needsFreshLocalKey ? randomSecret() : previous.cliProxyAPIKey
                profiles[index].cliProxyManagementKey = sharedManagementKey
                profiles[index].cliProxyAppliedSignature = nil
            } else if profiles[index].cliProxyAppliedSignature != nil {
                // Claude Code can point at only one custom profile at a time.
                // Keep saved credentials for switching, but do not keep another
                // profile marked active when models are intentionally unprefixed.
                profiles[index].cliProxyAppliedSignature = nil
            }
            if profiles[index] != previous {
                try BirdNionConfigStore.saveClaudeCodeProfile(profiles[index])
            }
        }

        guard let current = profiles.first(where: { $0.id == profile.id }) else {
            throw ServiceError.incompleteConfiguration
        }
        return current
    }

    static func activeProfiles(from profiles: [BirdNionConfigStore.ClaudeCodeProfile])
    -> [BirdNionConfigStore.ClaudeCodeProfile] {
        profiles.filter { $0.embeddedLocalProxy == true && $0.isCLIProxyConfigurationCurrent }
    }

    /// A profile created before the dedicated port must be re-applied so its
    /// Claude Code settings move with the local helper. Do not report it as on.
    private func migrateProfilesToCurrentPort(_ profiles: inout [BirdNionConfigStore.ClaudeCodeProfile]) throws -> Bool {
        var didMigrate = false
        for index in profiles.indices {
            guard Self.needsLocalPortMigration(profiles[index]) else {
                continue
            }
            profiles[index].cliProxyBaseURL = CLIProxyAPIConfiguration.localBaseURL
            profiles[index].cliProxyAppliedSignature = nil
            try BirdNionConfigStore.saveClaudeCodeProfile(profiles[index])
            didMigrate = true
        }
        return didMigrate
    }

    private func reload(profiles: [BirdNionConfigStore.ClaudeCodeProfile]) async throws {
        guard let configuration = CLIProxyAPIConfiguration(profiles: profiles, authDirectory: authDirectoryURL) else {
            throw ServiceError.incompleteConfiguration
        }
        try write(configuration: configuration)
        try await ensureRunning()
        try await CLIProxyAPIClient().synchronize(configuration)
    }

    private var configDirectoryURL: URL {
        BirdNionConfigStore.configURL()
            .deletingLastPathComponent()
            .appendingPathComponent("cli-proxy-api", isDirectory: true)
    }

    private var configURL: URL {
        configDirectoryURL.appendingPathComponent("config.yaml")
    }

    private var authDirectoryURL: URL {
        configDirectoryURL.appendingPathComponent("auth", isDirectory: true)
    }

    private func write(configuration: CLIProxyAPIConfiguration) throws {
        let manager = FileManager.default
        try manager.createDirectory(at: authDirectoryURL, withIntermediateDirectories: true)
        try manager.setAttributes([.posixPermissions: 0o700], ofItemAtPath: configDirectoryURL.path)
        try manager.setAttributes([.posixPermissions: 0o700], ofItemAtPath: authDirectoryURL.path)
        try configuration.yamlData().write(to: configURL, options: [.atomic])
        try? manager.setAttributes([.posixPermissions: 0o600], ofItemAtPath: configURL.path)
    }

    private func ensureRunning() async throws {
        if processController.isOwnedProcessRunning { return }
        if await isHealthy() { return }
        guard let executable = Bundle.main.url(forResource: "cliproxyapi", withExtension: nil) else {
            throw ServiceError.helperUnavailable
        }

        do {
            try processController.start(
                executable: executable,
                configURL: configURL,
                workingDirectory: configDirectoryURL
            )
        } catch {
            throw ServiceError.didNotStart
        }

        for _ in 0..<25 {
            if await isHealthy() { return }
            try await Task.sleep(nanoseconds: 200_000_000)
        }
        stop()
        throw ServiceError.didNotStart
    }

    private func isHealthy() async -> Bool {
        guard let url = URL(string: CLIProxyAPIConfiguration.localBaseURL + "/healthz") else { return false }
        var request = URLRequest(url: url)
        request.timeoutInterval = 1
        guard let (_, response) = try? await URLSession.shared.data(for: request),
              let http = response as? HTTPURLResponse else { return false }
        return (200..<300).contains(http.statusCode)
    }

    private func randomSecret() -> String {
        var bytes = [UInt8](repeating: 0, count: 32)
        guard SecRandomCopyBytes(kSecRandomDefault, bytes.count, &bytes) == errSecSuccess else {
            return UUID().uuidString.replacingOccurrences(of: "-", with: "")
        }
        return Data(bytes).base64EncodedString()
            .replacingOccurrences(of: "+", with: "-")
            .replacingOccurrences(of: "/", with: "_")
            .replacingOccurrences(of: "=", with: "")
    }

    private func cleaned(_ value: String?) -> String? {
        guard let value = value?.trimmingCharacters(in: .whitespacesAndNewlines), !value.isEmpty else { return nil }
        return value
    }
}
