import Foundation
import Security

/// Owns the bundled CLIProxyAPI core used by custom Claude Code profiles. The
/// helper only binds loopback, and both its API and management credentials are
/// generated by BirdNion rather than entered through the UI.
@MainActor
final class EmbeddedCLIProxyService {
    enum ServiceError: Error, Equatable {
        case incompleteConfiguration
        case helperUnavailable
        case didNotStart
    }

    static let shared = EmbeddedCLIProxyService()
    static let localEndpoint = CLIProxyAPIConfiguration.localBaseURL + "/v1"

    private var process: Process?

    private init() {}

    func prepare(profile: BirdNionConfigStore.ClaudeCodeProfile) async throws
    -> BirdNionConfigStore.ClaudeCodeProfile {
        guard profile.hasUpstreamConfiguration else { throw ServiceError.incompleteConfiguration }
        let (prepared, profiles) = try prepareProfiles(replacing: profile)
        try await reload(profiles: profiles)

        var applied = prepared
        applied.cliProxyAppliedSignature = applied.cliProxyConfigurationSignature
        try BirdNionConfigStore.saveClaudeCodeProfile(applied)
        return applied
    }

    /// Starts the local helper after app launch when a previously activated
    /// profile exists. Failures stay non-blocking because Settings can surface
    /// the precise error during the next explicit apply.
    func restoreIfConfigured() async {
        let profiles = BirdNionConfigStore.claudeCodeProfiles()
        guard profiles.contains(where: { $0.embeddedLocalProxy == true && $0.isEmbeddedCLIProxyReady }) else {
            return
        }
        do {
            try await reload(profiles: profiles)
        } catch {
            NSLog("BirdNion local proxy restore failed: %@", error.localizedDescription)
        }
    }

    /// Removes deleted profiles' upstream credentials and local API keys from
    /// the running helper immediately. No remaining embedded profile means the
    /// helper is no longer needed.
    func reconcileStoredProfiles() async {
        let profiles = BirdNionConfigStore.claudeCodeProfiles()
        guard profiles.contains(where: { $0.embeddedLocalProxy == true && $0.isEmbeddedCLIProxyReady }) else {
            stop()
            return
        }
        do {
            try await reload(profiles: profiles)
        } catch {
            NSLog("BirdNion local proxy reconciliation failed: %@", error.localizedDescription)
        }
    }

    func stop() {
        guard let process, process.isRunning else { return }
        process.terminate()
        self.process = nil
    }

    private func prepareProfiles(replacing profile: BirdNionConfigStore.ClaudeCodeProfile) throws
    -> (BirdNionConfigStore.ClaudeCodeProfile, [BirdNionConfigStore.ClaudeCodeProfile]) {
        var profiles = BirdNionConfigStore.claudeCodeProfiles()
        if let index = profiles.firstIndex(where: { $0.id == profile.id }) {
            profiles[index] = profile
        } else {
            profiles.append(profile)
        }

        let sharedManagementKey = profiles.compactMap { candidate -> String? in
            guard candidate.embeddedLocalProxy == true else { return nil }
            return cleaned(candidate.cliProxyManagementKey)
        }.first ?? randomSecret()

        for index in profiles.indices {
            let isCurrent = profiles[index].id == profile.id
            guard isCurrent || profiles[index].embeddedLocalProxy == true else { continue }
            guard profiles[index].hasUpstreamConfiguration else { continue }

            let previous = profiles[index]
            let needsFreshLocalKey = previous.embeddedLocalProxy != true || cleaned(previous.cliProxyAPIKey) == nil
            profiles[index].embeddedLocalProxy = true
            profiles[index].cliProxyBaseURL = CLIProxyAPIConfiguration.localBaseURL
            profiles[index].cliProxyAPIKey = needsFreshLocalKey ? randomSecret() : previous.cliProxyAPIKey
            profiles[index].cliProxyManagementKey = sharedManagementKey
            profiles[index].cliProxyAppliedSignature = nil
            if profiles[index] != previous {
                try BirdNionConfigStore.saveClaudeCodeProfile(profiles[index])
            }
        }

        guard let current = profiles.first(where: { $0.id == profile.id }) else {
            throw ServiceError.incompleteConfiguration
        }
        return (current, profiles)
    }

    private func reload(profiles: [BirdNionConfigStore.ClaudeCodeProfile]) async throws {
        guard let configuration = CLIProxyAPIConfiguration(profiles: profiles, authDirectory: authDirectoryURL) else {
            throw ServiceError.incompleteConfiguration
        }
        try write(configuration: configuration)
        try await ensureRunning()
        try await CLIProxyAPIClient().synchronize(configuration)
    }

    private var configDirectoryURL: URL {
        BirdNionConfigStore.configURL()
            .deletingLastPathComponent()
            .appendingPathComponent("cli-proxy-api", isDirectory: true)
    }

    private var configURL: URL {
        configDirectoryURL.appendingPathComponent("config.yaml")
    }

    private var authDirectoryURL: URL {
        configDirectoryURL.appendingPathComponent("auth", isDirectory: true)
    }

    private func write(configuration: CLIProxyAPIConfiguration) throws {
        let manager = FileManager.default
        try manager.createDirectory(at: authDirectoryURL, withIntermediateDirectories: true)
        try manager.setAttributes([.posixPermissions: 0o700], ofItemAtPath: configDirectoryURL.path)
        try manager.setAttributes([.posixPermissions: 0o700], ofItemAtPath: authDirectoryURL.path)
        try configuration.yamlData().write(to: configURL, options: [.atomic])
        try? manager.setAttributes([.posixPermissions: 0o600], ofItemAtPath: configURL.path)
    }

    private func ensureRunning() async throws {
        if process?.isRunning == true { return }
        if await isHealthy() { return }
        guard let executable = Bundle.main.url(forResource: "cliproxyapi", withExtension: nil) else {
            throw ServiceError.helperUnavailable
        }

        let process = Process()
        process.executableURL = executable
        process.arguments = ["-config", configURL.path, "-local-model"]
        process.currentDirectoryURL = configDirectoryURL
        process.standardOutput = FileHandle.nullDevice
        process.standardError = FileHandle.nullDevice
        do {
            try process.run()
        } catch {
            throw ServiceError.didNotStart
        }
        self.process = process

        for _ in 0..<25 {
            if await isHealthy() { return }
            try await Task.sleep(nanoseconds: 200_000_000)
        }
        stop()
        throw ServiceError.didNotStart
    }

    private func isHealthy() async -> Bool {
        guard let url = URL(string: CLIProxyAPIConfiguration.localBaseURL + "/healthz") else { return false }
        var request = URLRequest(url: url)
        request.timeoutInterval = 1
        guard let (_, response) = try? await URLSession.shared.data(for: request),
              let http = response as? HTTPURLResponse else { return false }
        return (200..<300).contains(http.statusCode)
    }

    private func randomSecret() -> String {
        var bytes = [UInt8](repeating: 0, count: 32)
        guard SecRandomCopyBytes(kSecRandomDefault, bytes.count, &bytes) == errSecSuccess else {
            return UUID().uuidString.replacingOccurrences(of: "-", with: "")
        }
        return Data(bytes).base64EncodedString()
            .replacingOccurrences(of: "+", with: "-")
            .replacingOccurrences(of: "/", with: "_")
            .replacingOccurrences(of: "=", with: "")
    }

    private func cleaned(_ value: String?) -> String? {
        guard let value = value?.trimmingCharacters(in: .whitespacesAndNewlines), !value.isEmpty else { return nil }
        return value
    }
}
