#!/bin/bash
# Regenerates CodexParserHash from the vendored Codex cost-usage parser.
#
# The Codex cost cache is keyed on this hash: a cached file whose bytes have not
# changed is never re-parsed, so a change to the counting logic that keeps the
# old hash silently never runs against history already on disk. Rotating the
# hash is what invalidates those caches.
#
# Run after ANY edit under Vendored/CostUsage/, then commit the generated file
# together with the change. `CodexParserHashTests` fails the build if you don't.
#
#   Scripts/regenerate-codex-parser-hash.sh          # rewrite the generated file
#   Scripts/regenerate-codex-parser-hash.sh --check  # verify only, non-zero if stale
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SOURCES="$ROOT/Vendor/CodexBar/Sources/CodexBarCore/Vendored/CostUsage"
GENERATED="$ROOT/Vendor/CodexBar/Sources/CodexBarCore/Generated/CodexParserHash.generated.swift"

if [ ! -d "$SOURCES" ]; then
  echo "error: parser sources not found at $SOURCES" >&2
  exit 1
fi

# Hash = sha256 over each .swift file in name order, feeding the file name and
# then its bytes. The name is included so a rename alone still rotates the hash.
# Keep this byte-for-byte identical to CodexParserHashTests.expectedHash().
compute() {
  local file
  # LC_ALL=C so the order is byte order: a locale-aware sort ignores the `+`
  # in "CostUsageScanner+CacheHelpers.swift" and yields a different digest.
  find "$SOURCES" -maxdepth 1 -name '*.swift' | LC_ALL=C sort | while IFS= read -r file; do
    printf '%s' "$(basename "$file")"
    cat "$file"
  done | shasum -a 256 | cut -c1-16
}

HASH="$(compute)"
CURRENT="$(sed -n 's/.*static let value = "\([0-9a-f]*\)".*/\1/p' "$GENERATED")"

if [ "${1:-}" = "--check" ]; then
  if [ "$HASH" = "$CURRENT" ]; then
    echo "CodexParserHash is current ($HASH)"
    exit 0
  fi
  echo "error: CodexParserHash is stale." >&2
  echo "  generated file: $CURRENT" >&2
  echo "  parser sources: $HASH" >&2
  echo "  run Scripts/regenerate-codex-parser-hash.sh and commit the result" >&2
  exit 1
fi

cat > "$GENERATED" <<GENERATED_SWIFT
// Generated by Scripts/regenerate-codex-parser-hash.sh. Do not edit by hand.

enum CodexParserHash {
    static let value = "$HASH"
}
GENERATED_SWIFT

if [ "$HASH" = "$CURRENT" ]; then
  echo "CodexParserHash unchanged ($HASH)"
else
  echo "CodexParserHash $CURRENT -> $HASH"
fi
